### ISSUE TITLE
How do I compile the files?

### ISSUE THREAD

**Issue by nullDorito** [SotaJoe/EAS-Encoder#11]
I've put the .sln files in and built everything, but I can't find any .exe files. Am I doing something wrong? Anyone who's set this up recently, can you give me the full process of setup?

EDIT: I've also seen things about the library/winform files, but I don't know what those are.
![image](https://user-images.githubusercontent.com/68170554/174462114-849d3f9d-adea-4b4b-b29e-39f1e3bad0f2.png)

**Comment by sasquelch** [comment]
I don't closely watch this project anymore, but it still compiles and runs fine in the latest version of Visual Studio. You simply need to set the test app as the startup project. This is what the error message is trying to convey, but it's definitely not obvious! :) 

To build and run this project in Visual Studio, make ABSOLUTELY CERTAIN that you've set the "EASEncoder Test App" project as the startup project or you'll get an error when you try to compile and run.

To set the startup project:

    In Solution Explorer, select the solution (the top node).
    Highlight the project "EASEncoder Test App", right-click on it.
    From the pop-up menu, select "Set As Startup Project."

You're now ready to build and run - Enjoy!

**Comment by nullDorito** [comment]
Thank you!
