### ISSUE TITLE
App will not compile

### ISSUE THREAD

**Issue by THEWHITEBOY503** [SotaJoe/EAS-Encoder#3]
Am I doing anything wrong here? I can't get the program to compile. 

With default settings: ![Image](https://death.is-for.me/i/uk6e.png)
Using console/windows app: ![Image](https://death.is-for.me/i/rc28.png)

**Comment by sasquelch** [comment]
Howdy, Connor -

There are two projects you'll see in the solution explorer. One is the library project, the other is the winform app project. It looks like the library project is set as the startup project, and not the winform app. If you right click on the winform app project and click "Set as startup project", it will work for you when you run it. The error message means that it compiled and built for you, but it is literally trying to run the wrong project. (It would be like you clicking on .dll file on your desktop trying to start an application - it won't work.)

Hope that helps! :)

Joe Goldade
joegoldade@gmail.com

**Comment by THEWHITEBOY503** [comment]
That worked! Thank you!
