### ISSUE TITLE
Building is damaging my brain

### ISSUE THREAD

**Issue by snaildos** [SotaJoe/EAS-Encoder#7]
Hello there, I wanted to reach out to you and ask if you could possibly provide a pre-built binary and maybe upload it to "GitHub Releases"? It's a pain to compile it and it just doesn't work properly when I try.
I'd appreciate this very much.
Regards, SnailDOS

**Comment by SchattenWolf2008** [comment]
do you know how to compile this?
i have no idea how to do that... ._.

**Comment by fourteentrees** [comment]
This repo is dead.
Use Visual Studio to compile EAS Encoder Test App with the .sln file.

**Comment by snaildos** [comment]
>:(
It's a nightmare to compile because of the fact it requires modules. I'm struggling to compile it.

**Comment by snaildos** [comment]
I added NAudio with nuget, and it's saying namespace could not be found.

**Comment by Moonbase2004** [comment]
Hi Snail

I can compile the test app for you and send it over discord. Please DM me at Moonbase__#9060

**Comment by snaildos** [comment]
Yo! Tysm so much for that. Will be contacting you now.

**Comment by snaildos** [comment]
I just can't friend you to dm you since you have friends off. Friend me, SnailDOS#9905.

**Comment by SchattenWolf2008** [comment]
I managed it to build it.
Well, i cant do anything with that.
I dont have an script on my raspberry pi that can generate the needed signal
And I think this wont work bc I live in germany.
