### ISSUE TITLE
Can't compile the program

### ISSUE THREAD

**Issue by TheEndlessKing** [SotaJoe/EAS-Encoder#8]
Hello, how can I compile this? The modules I need for it to work aren't there. I can't get the modules for it to work. Thanks for any help in advance.

**Comment by sasquelch** [comment]
Hi, there! I just pulled the code and opened it in Visual Studio - it compiled successfully for me. Make sure the EASEncoder Test App is "Set as Startup Project", or else the app won't run after build. There are also NuGet packages that need to be pulled (these were pulled automatically during build for me). Make sure your permissions allow NuGet to pull the packages it needs.

**Comment by TheEndlessKing** [comment]
Thanks! Worked perfectly.
